registries:
  python-gcp:
    password: ${{secrets.ARTIFACT_REGISTRY_PASSWD}}
    type: python-index
    url: https://asia-east1-python.pkg.dev/living-bio/livingbio-pypi/simple/
    username: _json_key_base64
updates:
- allow:
  - dependency-type: all
  directory: /
  insecure-external-code-execution: allow
  package-ecosystem: uv
  registries:
  - python-gcp
  schedule:
    interval: daily
version: 2
